/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MapRouteImport } from './routes/map'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIdRouteImport } from './routes/store.$id'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedCreateStoreRouteImport } from './routes/_authenticated/create-store'
import { Route as AuthenticatedStoreIdReviewRouteImport } from './routes/_authenticated/store.$id.review'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateStoreRoute =
  AuthenticatedCreateStoreRouteImport.update({
    id: '/create-store',
    path: '/create-store',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStoreIdReviewRoute =
  AuthenticatedStoreIdReviewRouteImport.update({
    id: '/store/$id/review',
    path: '/store/$id/review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/create-store': typeof AuthenticatedCreateStoreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/profile/$id': typeof ProfileIdRoute
  '/store/$id': typeof StoreIdRoute
  '/store/$id/review': typeof AuthenticatedStoreIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/create-store': typeof AuthenticatedCreateStoreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/profile/$id': typeof ProfileIdRoute
  '/store/$id': typeof StoreIdRoute
  '/store/$id/review': typeof AuthenticatedStoreIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/map': typeof MapRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/create-store': typeof AuthenticatedCreateStoreRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/profile/$id': typeof ProfileIdRoute
  '/store/$id': typeof StoreIdRoute
  '/_authenticated/store/$id/review': typeof AuthenticatedStoreIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/sign-in'
    | '/sign-up'
    | '/create-store'
    | '/profile'
    | '/profile/$id'
    | '/store/$id'
    | '/store/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/sign-in'
    | '/sign-up'
    | '/create-store'
    | '/profile'
    | '/profile/$id'
    | '/store/$id'
    | '/store/$id/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/map'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/create-store'
    | '/_authenticated/profile'
    | '/profile/$id'
    | '/store/$id'
    | '/_authenticated/store/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  MapRoute: typeof MapRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ProfileIdRoute: typeof ProfileIdRoute
  StoreIdRoute: typeof StoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-store': {
      id: '/_authenticated/create-store'
      path: '/create-store'
      fullPath: '/create-store'
      preLoaderRoute: typeof AuthenticatedCreateStoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/store/$id/review': {
      id: '/_authenticated/store/$id/review'
      path: '/store/$id/review'
      fullPath: '/store/$id/review'
      preLoaderRoute: typeof AuthenticatedStoreIdReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCreateStoreRoute: typeof AuthenticatedCreateStoreRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStoreIdReviewRoute: typeof AuthenticatedStoreIdReviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreateStoreRoute: AuthenticatedCreateStoreRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStoreIdReviewRoute: AuthenticatedStoreIdReviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  MapRoute: MapRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ProfileIdRoute: ProfileIdRoute,
  StoreIdRoute: StoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
